### ISSUE TITLE
2.0 raodmap

### ISSUE THREAD

**Issue by trevorwang** [trevorwang/retrofit.dart#184]
- [ ]  converters support, to move data serialization out of generator #183
- [ ] isolate support on Flutter  #164 
- [ ] named parameters in `annotation`
- [ ] adapters, Observable support e.g. #149 
- [ ] error handler to wrap DioError and others #168
